module.exports = {
  aluminium_worker: require('../images/png/aluminium_worker_r.png'),
  carpenter: require('../images/png/carpenter_r.png'),
  cleaner: require('../images/png/cleaner_r.png'),
  tutor: require('../images/png/teacher_r.png'),
  electrician: require('../images/png/electrician_r.png'),
  gardener: require('../images/png/farmer_r.png'),
  housekeeper: require('../images/png/housekeeper_r.png'),
  mechanic: require('../images/png/mechanic_r.png'),
  nanny: require('../images/png/nanny_r.png'),
  painter: require('../images/png/painter_r.png'),
  photographer: require('../images/png/photographer_r.png'),
  plasterer: require('../images/png/plasterer_r.png'),
  plumber: require('../images/png/plumber_r.png'),
  roofer: require('../images/png/roofer_r.png'),
  technician: require('../images/png/technician_r.png'),
  welder: require('../images/png/welder_r.png'),
};
