export const FETCHING_MESSAGES = 'FETCHING_MESSAGES';
export const FETCHED_MESSAGES = 'FETCHED_MESSAGES';
export const FETCHED_DB_MESSAGES = 'FETCHED_DB_MESSAGES';
export const FETCHING_MESSAGES_ERROR = 'FETCHING_MESSAGES_ERROR';
export const FETCHING_NOTIFICATIONS = 'FETCHING_NOTIFICATIONS';
export const FETCHED_NOTIFICATIONS = 'FETCHED_NOTIFICATIONS';
export const FETCHING_NOTIFICATIONS_ERROR = 'FETCHING_NOTIFICATIONS_ERROR';
export const FETCHING_GENERAL_INFO = 'FETCHING_GENERAL_INFO';
export const FETCHED_GENERAL_INFO = 'FETCHED_GENERAL_INFO';
export const FETCHING_GENERAL_INFO_ERROR = 'FETCHING_GENERAL_INFO_ERROR';
export const FETCHING_COORDINATES = 'FETCHING_COORDINATES';
export const FETCHED_COORDINATES = 'FETCHED_COORDINATES';
export const FETCHING_COORDINATES_ERROR = 'FETCHING_COORDINATES_ERROR';
export const FETCHING_OTHERS_COORDINATES = 'FETCHING_OTHERS_COORDINATES';
export const FETCHED_OTHERS_COORDINATES = 'FETCHED_OTHERS_COORDINATES';
export const FETCHING_OTHERS_COORDINATES_ERROR =
  'FETCHING_OTHERS_COORDINATES_ERROR';
export const FETCHING_JOB_REQUESTS = 'FETCHING_JOB_REQUESTS';
export const FETCHED_JOB_REQUESTS = 'FETCHED_JOB_REQUESTS';
export const FETCHING_JOB_REQUESTS_ERROR = 'FETCHING_JOB_REQUESTS_ERROR';
export const FETCHING_JOB_REQUESTS_PROVIDERS =
  'FETCHING_JOB_REQUESTS_PROVIDERS';
export const FETCHED_JOB_REQUESTS_PROVIDERS = 'FETCHED_JOB_REQUESTS_PROVIDERS';
export const FETCHING_JOB_REQUESTS_PROVIDERS_ERROR =
  'FETCHING_JOB_REQUESTS_PROVIDERS_ERROR';
export const SET_SELECTED_JOB_REQUEST = 'SET_SELECTED_JOB_REQUEST';
export const FETCHED_ALL_JOB_REQUESTS_PRO = 'FETCHED_ALL_JOB_REQUESTS_PRO';
export const FETCH_ALL_JOB_REQUESTS_PRO_ERROR =
  'FETCH_ALL_JOB_REQUESTS_PRO_ERROR';
export const FETCHED_ALL_JOB_REQUESTS_CLIENT =
  'FETCHED_ALL_JOB_REQUESTS_CLIENT';
export const FETCH_ALL_JOB_REQUESTS_CLIENT_ERROR =
  'FETCH_ALL_JOB_REQUESTS_CLIENT_ERROR';
export const FETCHING_DATA_WORK_SOURCE = 'FETCHING_DATA_WORK_SOURCE';
export const FETCHED_DATA_WORK_SOURCE = 'FETCHED_DATA_WORK_SOURCE';
export const FETCH_DATA_WORK_SOURCE_ERROR = 'FETCH_DATA_WORK_SOURCE_ERROR';
export const UPDATE_ACTIVE_REQUREST = 'UPDATE_ACTIVE_REQUREST';
export const UPDATE_ONLINE_STATUS = 'UPDATE_ONLINE_STATUS';
export const UPDATE_CONNECTIVITY_STATUS = 'UPDATE_CONNECTIVITY_STATUS';
export const UPDATE_LIVE_CHAT_USERS = 'UPDATE_LIVE_CHAT_USERS';
export const UPDATE_PROVIDER_DETAILS = 'UPDATE_PROVIDER_DETAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const RESET_USER_DETAILS = 'RESET_USER_DETAILS';
export const UPDATE_NEW_USER_INFO = 'UPDATE_NEW_USER_INFO';
export const UPDATE_USER_AUTH_TOKEN = 'UPDATE_USER_AUTH_TOKEN';
export const UPDATE_PROVIDER_AUTH_TOKEN = 'UPDATE_PROVIDER_AUTH_TOKEN';
export const UPDATE_VALIDATION_CODE = 'UPDATE_VALIDATION_CODE';
export const UPDATE_NUMBER_SENT = 'UPDATE_NUMBER_SENT';
export const UPDATE_CONFIRMATION_OBJECT = 'UPDATE_CONFIRMATION_OBJECT';
export const RESET_VALIDATION = 'RESET_VALIDATION';
export const UPDATE_MOBILE_NUMBER = 'UPDATE_MOBILE_NUMBER';
export const UPDATE_COUNTRY_CODE = 'UPDATE_COUNTRY_CODE';
export const UPDATE_COUNTRY_ALPHA_2 = 'UPDATE_COUNTRY_ALPHA_2';
export const UPDATE_LATEST_CHATS = 'UPDATE_LATEST_CHATS';
export const SET_LATEST_CHATS_ERROR = 'SET_LATEST_CHATS_ERROR';
export const UPDATE_BOOKING_COMPLETE_DATA = 'UPDATE_BOOKING_COMPLETE_DATA';
export const UPDATE_REJECTED_BOOKINGS_DATA = 'UPDATE_REJECTED_BOOKINGS_DATA';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
